#!/usr/bin/env bash
# Regenerate css/app.css from the three source sheets.
# Run from the repo root: bash build-css.sh
set -euo pipefail

OUT="css/app.css"
echo "/* generated by build-css.sh — do NOT edit directly */" > "$OUT"
cat css/style.css css/modern.css css/theme-crimson.css >> "$OUT"
echo "Built $OUT"
